backend = "xrender";
vsync = false;
shadow = true;
shadow-radius = 7;
shadow-opacity = 0.7;
corner-radius = 10;
# Принудительно включаем закругленные углы для Kitty
corner-radius-rules = (
    "10:class_g = 'kitty'"
);
